### ISSUE TITLE
Add persistent CLI access to the Jailbreak page on the wiki

### ISSUE THREAD

**Issue by ben-kuhn** [mdubinko/gsoc-contrib#15]
Persistent terminal access is quite easy to get (without booting from the SD card.)

The following can be added to the bottom of the "Jailbreak" wiki page.

**Modify /mnt/emmc_p2/etc/inittab for persistent terminal access**

Add the following under "#Put a getty on the serial port"
```
tty2::respawn:/sbin/getty -L tty2 0 vt100
tty3::respawn:/sbin/getty -L tty3 0 vt100
tty4::respawn:/sbin/getty -L tty4 0 vt100
tty5::respawn:/sbin/getty -L tty5 0 vt100
```

This will allow you to access the shell by pressing ctrl+alt+f2, f3, through f5.  Ctrl+alt+f1 will switch back to the regular GSOC gui.

**Change the root password**

You will need to change the root password in order to log in.  You can do that with the following commands:
```
chroot /mnt/emmc_p2
passwd root
```
Enter a strong root password

**Comment by d3cker** [comment]
This helps to save a time. Thank you. 
I agree, this should be in the wiki.

**Comment by ben-kuhn** [comment]
The wiki has been updated.  Closing my own issue :-)
